# Generated by Django 4.1.3 on 2022-12-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
