# Generated by Django 4.1.3 on 2023-02-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tag',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
