# Generated by Django 4.0.6 on 2022-08-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_code',
            field=models.CharField(default='8ehixip8xsj2n198ke14', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='e39m2cpnnta6ll7fb8sx', max_length=20),
        ),
    ]
