# Generated by Django 4.1.3 on 2023-03-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='20h4eqh0r9apc0x4g8qa', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='u42n127c1yiztemcw7g0', max_length=20),
        ),
    ]
