# Generated by Django 4.1.3 on 2023-03-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_comment_code_alter_post_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='x9c704w2720uiwpnkm6d', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='bggmgrzmgce4dd1ru66r', max_length=20),
        ),
    ]
