# Generated by Django 4.0.6 on 2022-10-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comments_comment_code_alter_post_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_code',
            field=models.CharField(default='4aguhmlojlkn5uapyq5a', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='cdqwd2q29x87qms4ybnr', max_length=20),
        ),
    ]
