# Generated by Django 4.1.3 on 2023-03-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_comment_code_alter_post_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='y6xy19hhk79uoa9r6myl', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='3vmgm8jnz7cl8g36mxr6', max_length=20),
        ),
    ]
