# Generated by Django 4.0.6 on 2022-10-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comments_comment_code_alter_post_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_code',
            field=models.CharField(default='pr6jpnst1zydt7lnugaw', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='1v691tcko748w6felz0l', max_length=20),
        ),
    ]
