# Generated by Django 4.0.6 on 2022-10-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comments_comment_code_alter_post_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_code',
            field=models.CharField(default='4giavia8hppokfhuplya', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='q6oimvxp1mxnr8ml4qyr', max_length=20),
        ),
    ]
