# Generated by Django 4.1.3 on 2022-12-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_parent_alter_comment_comment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='tvdbrf1kdfk7i31j8osn', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='j2ywmad927ltnigsz49z', max_length=20),
        ),
    ]
