# Generated by Django 4.1.3 on 2022-12-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_comment_code_alter_post_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='371dup8iqmv1eh72748y', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='vv1ojb3jtgsaxroiedpa', max_length=20),
        ),
    ]
