# Generated by Django 4.1.3 on 2022-12-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_comment_comment_code_alter_post_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='2vkmau8u7uofinv3t2e8', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='8m3vc709fqs54rv5rsy5', max_length=20),
        ),
    ]
