# Generated by Django 4.1.3 on 2022-12-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_comment_code_alter_post_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='1dvveo7snjl38r6r4cyr', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='uhgqyv2xw3hgw0jg1zrc', max_length=20),
        ),
    ]
