# Generated by Django 4.1.3 on 2022-12-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_comment_comment_code_alter_post_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='3ikvvtwna370kd3e4c5s', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='qsnqc4qo56fd4w881s5u', max_length=20),
        ),
    ]
