# Generated by Django 4.1.3 on 2023-01-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_image_alter_comment_comment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='zhtodioevo4gjmtz8cd9', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='3dgy88h1ak1430gc005i', max_length=20),
        ),
    ]
