# Generated by Django 4.1.3 on 2023-01-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_comment_comment_code_alter_post_post_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='retweeted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='p754mkt67cusjg87wo2z', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='esw76hir03kc7zpi3ggk', max_length=20),
        ),
    ]
