# Generated by Django 4.1.3 on 2023-01-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_retweeted_alter_comment_comment_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='ddoqfv93ztp973b8y2k4', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='q7v5fkqq96a9m14mra9w', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='tweet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
