# Generated by Django 4.1.3 on 2023-02-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_comment_comment_code_alter_post_post_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='5gp4cd13uukauf3jdrf8', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='asbl2znu8qz9t5mo8dj4', max_length=20),
        ),
    ]
