# Generated by Django 4.1.3 on 2023-02-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_comment_comment_code_alter_post_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_code',
            field=models.CharField(default='2w1sezfx0dqqdi7dfkhv', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_code',
            field=models.CharField(default='h0fdiaazuoplyaypd0t4', max_length=20),
        ),
    ]
